version: '3.7'

services:

  image-compressor:
    container_name: image-compressor
    build: .
    volumes:
      - './:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true