apiVersion: v1
kind: Service
metadata:
  name: image-compressor
  labels:
    name: image-compressor
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
      protocol: TCP
  selector:
    app: image-compressor